import os
import re

from typing import List, Optional

from langchain.tools import tool, BaseTool
from pydantic import BaseModel, Field


class PlanStep(BaseModel):

    index: int = Field(
        description="Numerical index of this PlanStep. Index begins at 1 and increments by 1 for each PlanStep. ",
        gt=0
    )
    prompt: str = Field(
        description="Instructions for this step, passed directly to the executing agent."
    )
    # TODO langchain tool needs a pydantic schema, maybe use BaseTool?
    tool_names: Optional[List[str]] = Field(
        description="The names of agent tools required for execution of this step."
                    "Only use tool names that are available in your tool listing."
    )
    parallel: bool = Field(
        description="Whether the step can be executed concurrently with adjacent PlanSteps."
    )
    child_steps: Optional[List['PlanStep']] = Field(
        description="Additional PlanSteps that should execute following completion of this PlanStep."
    )

# TODO is this deprecated? No warnings
PlanStep.update_forward_refs()

class Plan(BaseModel):

    steps: List[PlanStep] = Field(
        description="Sequential list of steps to be attempted in order of PlanStep index."
                    "At least 1 step is required."
    )



class PlanTool(BaseTool):
    """Tool to run shell commands."""

    process: Any = Field(default_factory=_get_default_bash_process)
    """Bash process to run commands."""

    name: str = "terminal"
    """Name of tool."""

    description: str = f"Run shell commands on this {_get_platform()} machine."
    """Description of tool."""

    args_schema: Type[BaseModel] = ShellInput
    """Schema for input arguments."""

    ask_human_input: bool = False
    """
    If True, prompts the user for confirmation (y/n) before executing
    a command generated by the language model in the bash shell.
    """

    def _run(
        self,
        commands: Union[str, List[str]],
        run_manager: Optional[CallbackManagerForToolRun] = None,
    ) -> str:
        """Run commands and return final output."""

        print(f"Executing command:\n {commands}")  # noqa: T201

        try:
            if self.ask_human_input:
                user_input = input("Proceed with command execution? (y/n): ").lower()
                if user_input == "y":
                    return self.process.run(commands)
                else:
                    logger.info("Invalid input. User aborted command execution.")
                    return None  # type: ignore[return-value]
            else:
                return self.process.run(commands)

        except Exception as e:
            logger.error(f"Error during command execution: {e}")
            return None  # type: ignore[return-value]
